name: Build

on:
  push:
    branches:
      - NONE  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  # Change this to the version of .NET you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyApplication
        path: ./bin/Release/net6.0/
