name: Build and Release

on: workflow_dispatch
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' # Update with your desired .NET version

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./ATCOnlineAlert

      - name: Build Application
        run: dotnet build --configuration Release
        working-directory: ./ATCOnlineAlert

      - name: Zip Artifacts
        run: |
          mkdir artifacts
          zip -r artifacts/app.zip bin/Release
        working-directory: ./ATCOnlineAlert
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApplication
          path: ./bin/Release/net6.0/
